language: "node_js"

dist: trusty

node_js:
  - "10.15.3"

cache: npm

services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env: 
  global:
    - APP_ENV=test
    - NODE_ENV=test
    - PORT=4750
    - JWT_KEY="secretMADNESScraseman25362454u7ttccfh"
    - USER="john@yahoo.com"
    - USER2="wick@gmail.com"
    - USER3="jmorris@hotmail.com"
    - PASSWORD="Whykillmydog12"
    - ADMIN="orlando@wayfarer.com"
    - ADMIN_PASSWORD="Wayfarer10"
    - PGPORT=5432
    - PGDATABASE="cfxoukza"
    - PGUSER="cfxoukza"
    - PGHOST="rajje.db.elephantsql.com"
    - PGPASSWORD="4SNz_bXunu-OFVHIJO4qbd8gUMhSFUO8"
before_script:  
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - "npm run nyc"

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false
